"""
Daily tech news digest — generated by Gemini, cached for 24 hours.
Refresh happens automatically at 06:00 UTC each day via background task.
On each daily refresh, previous articles and discussions are replaced.
Discussions are stored in-memory (per-process lifetime).
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import threading
import time
import uuid
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from traceon.server.auth import require_member

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/news", tags=["news"])

# ── Cache ──────────────────────────────────────────────────────────────────────
_CACHE_FILE      = Path(__file__).parent.parent.parent.parent / "news_cache.json"
_CACHE_TTL       = 24 * 3600   # 24 hours
_REFRESH_HOUR_UTC = 6           # Daily refresh at 06:00 UTC
_cache_lock      = threading.Lock()

# ── Discussions ────────────────────────────────────────────────────────────────
# {article_id: [{id, user_id, user_name, user_avatar, text, created_at}]}
_discussions: dict[str, list[dict]] = {}
_disc_lock = threading.Lock()


# ── Models ─────────────────────────────────────────────────────────────────────
class CommentCreate(BaseModel):
    text: str


# ── Gemini helper ──────────────────────────────────────────────────────────────
_PROMPT = """
You are a senior tech editor. Generate a daily digest of 12 significant tech developments — 3 per category: Agentic AI, Machine Learning, Companies, Coding.

Each article must reflect real, noteworthy trends or events based on your knowledge. Be technically accurate and insightful.

Return ONLY a valid JSON array (no markdown, no explanation, no trailing text) with exactly 12 objects using this schema:
[
  {
    "id": "<kebab-case-slug unique across all articles>",
    "title": "<compelling headline under 90 chars>",
    "summary": "<2-3 sentence informative summary>",
    "category": "<exactly one of: Agentic AI | Machine Learning | Companies | Coding>",
    "key_points": ["<point 1>", "<point 2>", "<point 3>"],
    "read_minutes": <integer 2-6>,
    "source_type": "<one of: Research | Industry | Open Source | Community>"
  }
]
""".strip()


def _extract_json_array(text: str) -> str:
    """Robustly extract a JSON array from Gemini response, handling fences and extra text."""
    text = text.strip()
    # Strip markdown code fences
    if "```" in text:
        # Find content between first ``` pair
        fence_match = re.search(r'```(?:json)?\s*([\s\S]*?)```', text)
        if fence_match:
            text = fence_match.group(1).strip()

    # Find the outermost JSON array
    match = re.search(r'\[[\s\S]*\]', text)
    if match:
        return match.group()
    return text


def _gemini_fetch_news() -> list[dict]:
    api_key = os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY not set")

    from google import genai
    from google.genai import types

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=_PROMPT,
        config=types.GenerateContentConfig(
            temperature=0.7,
            max_output_tokens=4096,
        ),
    )
    raw = response.text.strip()
    raw = _extract_json_array(raw)

    try:
        articles = json.loads(raw)
    except json.JSONDecodeError as e:
        logger.error("JSON parse failed. Raw response excerpt: %s…", raw[:300])
        raise ValueError(f"Failed to parse Gemini response as JSON: {e}") from e

    if not isinstance(articles, list):
        raise ValueError("Gemini returned non-list JSON")

    required = {"id", "title", "summary", "category", "key_points", "read_minutes", "source_type"}
    for a in articles:
        missing = required - set(a.keys())
        if missing:
            raise ValueError(f"Article missing fields: {missing}")

    return articles


# ── Cache I/O ──────────────────────────────────────────────────────────────────

def _load_cache() -> Optional[dict]:
    """Load cache only if within TTL."""
    try:
        if _CACHE_FILE.exists():
            data = json.loads(_CACHE_FILE.read_text())
            if time.time() - data.get("generated_at", 0) < _CACHE_TTL:
                return data
    except Exception as e:
        logger.warning("Failed to read news cache: %s", e)
    return None


def _load_any_cache() -> Optional[dict]:
    """Load cache regardless of TTL (stale fallback while refresh is in progress)."""
    try:
        if _CACHE_FILE.exists():
            return json.loads(_CACHE_FILE.read_text())
    except Exception as e:
        logger.warning("Failed to read stale news cache: %s", e)
    return None


def _save_cache(articles: list[dict]) -> dict:
    data = {"generated_at": time.time(), "articles": articles}
    try:
        _CACHE_FILE.write_text(json.dumps(data, indent=2))
    except Exception as e:
        logger.warning("Failed to write news cache: %s", e)
    return data


def _do_refresh() -> dict:
    """Fetch fresh news, replace cache, and purge old discussions."""
    logger.info("Fetching fresh news digest from Gemini…")
    articles = _gemini_fetch_news()
    data = _save_cache(articles)

    # Clear discussions — old article IDs are gone
    with _disc_lock:
        _discussions.clear()

    logger.info("News digest refreshed: %d articles", len(articles))
    return data


# ── Background scheduler ───────────────────────────────────────────────────────

def _seconds_until_next_refresh() -> float:
    """Seconds until next 06:00 UTC."""
    now = datetime.now(timezone.utc)
    target = now.replace(hour=_REFRESH_HOUR_UTC, minute=0, second=0, microsecond=0)
    if now >= target:
        target += timedelta(days=1)
    return (target - now).total_seconds()


async def _news_refresh_loop():
    """Background task: bootstrap if stale, then refresh every day at 06:00 UTC."""
    # On startup: fetch immediately if no valid cache exists
    with _cache_lock:
        if _load_cache() is None:
            try:
                _do_refresh()
                logger.info("Initial news digest generated on startup")
            except Exception as e:
                logger.error("Startup news fetch failed: %s", e)

    while True:
        wait = _seconds_until_next_refresh()
        logger.info("Next news refresh in %.0fs (at 06:00 UTC)", wait)
        await asyncio.sleep(wait)
        with _cache_lock:
            try:
                _do_refresh()
            except Exception as e:
                logger.error("Scheduled news refresh failed: %s", e)


def start_news_scheduler():
    """Call from the app lifespan to launch the daily refresh background task."""
    asyncio.create_task(_news_refresh_loop())


# ── Endpoints ──────────────────────────────────────────────────────────────────

@router.get("")
async def get_news(user=Depends(require_member)):
    """Return the daily news digest from cache (never triggers a live Gemini call)."""
    with _cache_lock:
        data = _load_cache() or _load_any_cache()
    if not data:
        raise HTTPException(
            status_code=503,
            detail="News digest is being generated — please try again in a moment"
        )
    return {
        "articles":     data["articles"],
        "generated_at": data["generated_at"],
        "next_refresh": data["generated_at"] + _CACHE_TTL,
    }


@router.get("/{article_id}/comments")
async def get_comments(article_id: str, user=Depends(require_member)):
    with _disc_lock:
        return {"comments": _discussions.get(article_id, [])}


@router.post("/{article_id}/comments")
async def post_comment(article_id: str, body: CommentCreate, user=Depends(require_member)):
    text = body.text.strip()
    if not text:
        raise HTTPException(status_code=400, detail="Comment text cannot be empty")
    if len(text) > 1000:
        raise HTTPException(status_code=400, detail="Comment too long (max 1000 chars)")

    comment = {
        "id":          uuid.uuid4().hex,
        "article_id":  article_id,
        "user_id":     user.get("sub") or user.get("user_id", ""),
        "user_name":   user.get("name", "Member"),
        "user_avatar": user.get("picture", ""),
        "text":        text,
        "created_at":  time.time(),
    }

    with _disc_lock:
        _discussions.setdefault(article_id, []).append(comment)

    return {"comment": comment}
